name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client image
        run: |
          docker build -t ashals/task-manager-client:latest ./client
          docker push ashals/task-manager-client:latest

      - name: Build and push server image
        run: |
          docker build -t ashals/task-manager-server:latest ./server
          docker push ashals/task-manager-server:latest
